### PR TITLE
Update links to repository with files and add option to clone the repository

### LINKED ISSUE #10: Update Link to repository with necessary files
Currently https://github.com/awesome-workshop/payload/ is given as a link to the repository containing files (in setup). 

In hsf-training we have https://github.com/hsf-training/hsf-training-cms-analysis which contains all the files, hence it might be good to update the link to hsf repo?

### PR DESCRIPTION
**Pull request by amanmdesai**
Closes #10

### CODE REVIEW

**Comment by klieret** [comment]
Thanks a lot! 

Just one quick thing that I've noticed if you do the `curl` variant, the folder is called differently with suffix `-master` at the end. Do you think this will impact the rest of the lesson? Should we have a rename step afterwards (either there or for the `git` command, depending on what is needed?)

**Comment by amanmdesai** [comment]
Yes indeed I have been thinking about it. 
It wont impact the lessons. 
But can make the setup procedure a bit confusing.

There is also some inconsistency in instructions on docker. (its not incorrect but maybe confusing for someone)

For the curl, maybe for now we can add ```bash cd hsf-training-cms-analysis-master```  as an additional instruction?

**Comment by klieret** [comment]
Actually, how about we only leave the git instruction? I don't see why you would *not* want the git repository with it and this would make the instructions shorter (and they *have* seen git before, they have *not* seen curl, so this would also be easier, right?)

**Comment by amanmdesai** [comment]
Yes thats easier.

**Review by klieret — APPROVED** [review]
Thanks again!

**Pull request merged**
