### PR TITLE
update readme using cookicutter

### LINKED ISSUE #8: Update readme

### PR DESCRIPTION
**Pull request by amanmdesai**
Hi @klieret  I have just updated the README using the cookiecutter template

Closes #8

### CODE REVIEW

**Review by klieret — APPROVED** [review]
Thanks a lot! This is a great help :)

**Comment by klieret** [comment]
We might want to check that the links are working (we could simply copy the link-checker workflow from the template)

**Comment by amanmdesai** [comment]
> We might want to check that the links are working (we could simply copy the link-checker workflow from the template)

yeah that's useful.
I have now added that file directly to gh-pages.

**Comment by amanmdesai** [comment]
many links are failing 
https://github.com/hsf-training/hsf-training-cms-analysis-webpage/actions/runs/3806379439/jobs/6475122933

**Pull request merged**
